"""v3 candidate substrates S0-S4 — biologically defined, with recordable provenance.

Pre-registered in `docs/v3_preregistration.md` §2. Each candidate is generated by a declared
cell-type/pathway rule from the delivered annotation and adjacency; **none is produced by
searching for a good score**, and no candidate generator may read a food label, a dataset
metric, or the test split.

The provenance requirement (owner's constraint 5) is that a reader must be able to ask
"**why was this node added?**" and get a machine-checkable answer, not just a final node
list. Every candidate therefore records:

* ``selection_rule`` -- the declared rule, verbatim;
* ``seed_populations`` and ``added_populations`` -- which cell types seeded it and which
  were admitted by expansion;
* ``frontier_rule`` and ``cap_rule``;
* ``typed_composition`` -- per-class node counts;
* ``admission_reason`` -- a per-node reason, aggregated to ``{reason: count}`` so the
  answer is auditable without shipping a 1000-row table;
* ``node_list_sha256`` / ``edge_list_sha256`` -- identity of the exact sets.

The five candidates:

======  ==========================================================================
S0      the v2 substrate: ORN-seeded expansion over ORN -> PN -> KC/LH -> MBON/DAN
S1      S0's populations plus the higher-order neurons that have real edges BACK
        into PN or KC (feedback closure)
S2      MB/KC-centred: seed = KC and MBON, expanded along KC <-> MBON <-> DAN real
        edges, with ORN/PN attached by their real ORN->PN edges
S3      S0's populations plus the DAN and MBON neurons that close loops onto KC
S4      the union of S1 and S3 populations, capped by S0's declared frontier rule
======  ==========================================================================
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass, field
from typing import Any

import numpy as np
import scipy.sparse as sp

from drososense.connectome_selection import (
    LAYER_EXPANSION_GROUPS,
    expand_from_orns,
    orn_budget,
)

#: The declared candidates, in the order the pre-registration lists them.
CANDIDATE_IDS: tuple[str, ...] = ("S0", "S1", "S2", "S3", "S4")


class CandidateError(ValueError):
    """Raised when a candidate cannot be generated as declared."""


@dataclass(frozen=True)
class CandidateSubstrate:
    """One candidate substrate and the provenance behind it."""

    candidate_id: str
    node_indices: np.ndarray
    root_ids: np.ndarray
    adjacency: sp.csr_matrix
    input_rows: np.ndarray
    provenance: dict[str, Any]

    @property
    def n_nodes(self) -> int:
        return int(self.node_indices.size)

    @property
    def n_edges(self) -> int:
        return int(self.adjacency.nnz)


def _sha256_array(arr: np.ndarray) -> str:
    return hashlib.sha256(np.ascontiguousarray(arr, dtype=np.int64).tobytes()).hexdigest()


def _sha256_edges(matrix: sp.csr_matrix) -> str:
    coo = matrix.tocoo()
    digest = hashlib.sha256()
    digest.update(np.ascontiguousarray(coo.row.astype(np.int64)).tobytes())
    digest.update(np.ascontiguousarray(coo.col.astype(np.int64)).tobytes())
    return digest.hexdigest()


def _frontier_order(matrix: sp.csr_matrix, root_ids: np.ndarray, selected: np.ndarray) -> list[int]:
    """Candidates of a node set, ordered by cumulative synapse mass to it, ties by root id.

    This is S0's declared frontier rule, reused verbatim by the feedback candidates so
    they differ from S0 only in *which populations* are admissible.
    """
    score = np.zeros(matrix.shape[0], dtype=np.float64)
    in_selected = np.zeros(matrix.shape[0], dtype=bool)
    in_selected[selected] = True
    csc = matrix.tocsc()
    for row in selected.tolist():
        score += np.asarray(matrix[row].todense()).ravel()
        score += np.asarray(csc[:, row].todense()).ravel()
    return [
        int(r)
        for r in sorted(
            np.flatnonzero(~in_selected).tolist(),
            key=lambda r: (-float(score[r]), int(root_ids[r])),
        )
    ]


def _frontier_scores(matrix: sp.csr_matrix, selected: np.ndarray) -> np.ndarray:
    """The declared frontier score for EVERY node: cumulative synapse mass to ``selected``."""
    score = np.zeros(matrix.shape[0], dtype=np.float64)
    csc = matrix.tocsc()
    for row in selected.tolist():
        score += np.asarray(matrix[row].todense()).ravel()
        score += np.asarray(csc[:, row].todense()).ravel()
    return score


def _cap_by_frontier(
    matrix: sp.csr_matrix,
    root_ids: np.ndarray,
    admissible: np.ndarray,
    target_n: int,
) -> tuple[np.ndarray, dict[str, int]]:
    """Take ``target_n`` nodes from ``admissible`` in frontier order, seeded by nothing.

    Used by S2, which has no ORN phase: the whole admissible set is ordered by interior
    synapse mass and capped. Returns the kept rows and the admission-reason counts.
    """
    admissible = np.asarray(sorted(set(admissible.tolist())), dtype=np.int64)
    if admissible.size <= target_n:
        return admissible, {"admissible_smaller_than_cap": int(admissible.size)}
    # order by total degree within the admissible set (declared, result-blind)
    sub = matrix[admissible][:, admissible]
    deg = np.asarray(sub.getnnz(axis=0)).ravel() + np.asarray(sub.getnnz(axis=1)).ravel()
    order = sorted(range(admissible.size), key=lambda i: (-int(deg[i]), int(root_ids[admissible[i]])))
    kept = np.sort(admissible[[order[i] for i in range(target_n)]])
    return kept, {"degree_order_within_admissible": int(target_n)}


def _feedback_closure(
    matrix: sp.csr_matrix,
    root_ids: np.ndarray,
    classes: np.ndarray,
    base_rows: np.ndarray,
    *,
    source_classes: tuple[str, ...],
    target_classes: tuple[str, ...],
) -> np.ndarray:
    """Nodes of ``source_classes`` that have a real edge INTO a node of ``target_classes``.

    The declared feedback rule for S1 and S3: a candidate admits a higher-order / DAN /
    MBON neuron when it has a real edge back onto the pathway's intrinsic populations
    (PN or KC), which is what makes it part of a closed loop rather than a sink.
    """
    base = set(int(r) for r in base_rows.tolist())
    target_rows = {int(r) for r in np.flatnonzero(np.isin(classes, list(target_classes))).tolist()}
    coo = matrix.tocoo()
    admitted: set[int] = set()
    for src, dst in zip(coo.row.tolist(), coo.col.tolist()):
        # admit a node of a SOURCE class whose real edge lands INTO the base node set
        if int(dst) in base and str(classes[int(src)]) in source_classes:
            admitted.add(int(src))
    return np.asarray(sorted(admitted), dtype=np.int64)


def _provenance(
    *,
    candidate_id: str,
    selection_rule: str,
    seed_populations: dict[str, int],
    added_populations: dict[str, int],
    frontier_rule: str,
    cap_rule: str,
    classes: np.ndarray,
    node_rows: np.ndarray,
    adjacency: sp.csr_matrix,
    admission_reason: dict[str, int],
    extra: dict[str, Any] | None = None,
) -> dict[str, Any]:
    composed = {str(c): int((classes[node_rows] == c).sum()) for c in sorted(set(classes[node_rows].tolist()))}
    payload = {
        "candidate_id": candidate_id,
        "selection_rule": selection_rule,
        "seed_populations": {k: int(v) for k, v in sorted(seed_populations.items())},
        "added_populations": {k: int(v) for k, v in sorted(added_populations.items())},
        "frontier_rule": frontier_rule,
        "cap_rule": cap_rule,
        "typed_composition": composed,
        "admission_reason": {k: int(v) for k, v in sorted(admission_reason.items())},
        "n_nodes": int(node_rows.size),
        "n_edges": int(adjacency.nnz),
        "node_list_sha256": _sha256_array(node_rows),
        "edge_list_sha256": _sha256_edges(adjacency),
    }
    if extra:
        payload.update(extra)
    return payload


def generate_candidate(
    candidate_id: str,
    *,
    raw_graph: sp.csr_matrix,
    root_ids: np.ndarray,
    annotation,
    din: int = 5,
    target_n: int = 1000,
    seed: int = 0,
) -> CandidateSubstrate:
    """Generate one pre-registered candidate substrate.

    Args:
        candidate_id: One of :data:`CANDIDATE_IDS`.
        raw_graph: The full delivered adjacency (raw synapse counts).
        root_ids: Root ids in the graph's row order.
        annotation: The declared cell-type annotation.
        din: Input channel count (sets S0's ORN budget rule).
        target_n: The substrate size cap.
        seed: The declared seed (S0's expansion and the input map both use it).

    Returns:
        A :class:`CandidateSubstrate` with its provenance.

    Raises:
        CandidateError: On an unknown id, or when a candidate's declared populations are
            absent from the graph.
    """
    if candidate_id not in CANDIDATE_IDS:
        raise CandidateError(f"unknown candidate {candidate_id!r}; declared: {list(CANDIDATE_IDS)}")
    classes = annotation.class_of(root_ids)

    # ---- S0: the v2 substrate (the baseline candidate) --------------------
    s0 = expand_from_orns(raw_graph, root_ids, annotation, target_n, din=din, seed=seed)
    s0_rows = np.asarray(sorted(s0.node_indices.tolist()), dtype=np.int64)

    if candidate_id == "S0":
        adjacency = raw_graph[s0_rows][:, s0_rows].tocsr()
        prov = _provenance(
            candidate_id="S0",
            selection_rule=(
                "v2 substrate: ORN-seeded deterministic expansion over "
                "ORN -> PN -> KC/higher_order -> MBON/DAN, frontier by cumulative synapse "
                "mass with ties by root id, induced edges kept"
            ),
            seed_populations={"ORN": int((classes[s0_rows] == "ORN").sum())},
            added_populations={
                c: int((classes[s0_rows] == c).sum())
                for c in ("PN", "KC", "higher_order", "MBON", "DAN")
            },
            frontier_rule="cumulative synapse mass to the selected set, ties by root id",
            cap_rule=f"target_n={target_n}; 'other' nodes never admitted",
            classes=classes,
            node_rows=s0_rows,
            adjacency=adjacency,
            admission_reason=dict(s0.detail.get("layer_counts", {})),
            extra={"orn_budget": int(s0.detail["orn_budget"])},
        )
        return CandidateSubstrate(
            "S0", s0_rows, root_ids[s0_rows], adjacency,
            _input_rows(classes, s0_rows), prov,
        )

    # ---- S1 / S3 / S4: S0's populations plus a declared feedback closure ---
    if candidate_id in ("S1", "S3", "S4"):
        closures: list[tuple[str, np.ndarray]] = []
        if candidate_id in ("S1", "S4"):
            h = _feedback_closure(
                raw_graph, root_ids, classes, s0_rows,
                source_classes=("higher_order",), target_classes=("PN", "KC"),
            )
            closures.append(("higher_order_feedback_into_PN_or_KC", h))
        if candidate_id in ("S3", "S4"):
            d = _feedback_closure(
                raw_graph, root_ids, classes, s0_rows,
                source_classes=("DAN", "MBON"), target_classes=("KC",),
            )
            closures.append(("DAN_or_MBON_feedback_into_KC", d))
        admitted = np.asarray(
            sorted(set().union(*[set(c.tolist()) for _, c in closures])), dtype=np.int64
        ) if closures else np.zeros(0, dtype=np.int64)
        if admitted.size == 0:
            raise CandidateError(
                f"{candidate_id}: the declared feedback closure admitted no node; the "
                f"candidate cannot be generated as declared"
            )
        union = sorted(set(s0_rows.tolist()) | set(admitted.tolist()))
        merged = np.asarray(union, dtype=np.int64)
        # Cap by the DECLARED frontier rule applied to the union: every node competes on the
        # same score, so a feedback neuron with real edges into the core can displace S0's
        # weakest frontier node. (Keeping S0's nodes first would make S1/S3/S4 identical to
        # S0 whenever S0 already fills the cap -- which is what the first v3 run measured.)
        if merged.size > target_n:
            scores = _frontier_scores(raw_graph, s0_rows)
            ranked = sorted(
                union, key=lambda r: (-float(scores[r]), int(root_ids[r]))
            )[:target_n]
            merged = np.asarray(sorted(ranked), dtype=np.int64)
            n_displaced = int(len(set(s0_rows.tolist()) - set(merged.tolist())))
        else:
            n_displaced = 0
        adjacency = raw_graph[merged][:, merged].tocsr()
        prov = _provenance(
            candidate_id=candidate_id,
            selection_rule=(
                "S0's ORN-seeded expansion, plus "
                + " and ".join(rule for rule, _ in closures)
                + " (a real edge from the source population onto the pathway's intrinsic "
                "populations), induced edges kept"
            ),
            seed_populations={"ORN": int((classes[s0_rows] == "ORN").sum())},
            added_populations={
                c: int((classes[merged] == c).sum()) for c in ("PN", "KC", "higher_order", "MBON", "DAN")
            },
            frontier_rule="S0's closed; feedback nodes capped in S0 frontier order",
            cap_rule=f"target_n={target_n}",
            classes=classes,
            node_rows=merged,
            adjacency=adjacency,
            admission_reason={
                **{f"seed:{k}": int(v) for k, v in s0.detail.get("layer_counts", {}).items()},
                **{rule: int(rows.size) for rule, rows in closures},
            },
            extra={
                "n_merged_from_S0": int(s0_rows.size),
                "n_feedback_admitted": int(admitted.size),
                "n_S0_nodes_displaced_by_feedback": int(n_displaced),
                "n_feedback_nodes_in_final_set": int(
                    len(set(merged.tolist()) & set(admitted.tolist()))
                ),
            },
        )
        return CandidateSubstrate(
            candidate_id, merged, root_ids[merged], adjacency,
            _input_rows(classes, merged), prov,
        )

    # ---- S2: MB/KC-centred recurrent ------------------------------------
    if candidate_id == "S2":
        kc_mbon_rows = np.flatnonzero(np.isin(classes, ["KC", "higher_order", "MBON", "DAN"]))
        if kc_mbon_rows.size == 0:
            raise CandidateError("S2: the graph carries no KC/MBON/DAN population")
        # attach ORN/PN by their real ORN->PN edges: keep ORNs and the PNs an ORN reaches
        coo = raw_graph.tocoo()
        orn_rows = set(np.flatnonzero(classes == "ORN").tolist())
        pn_rows = set(np.flatnonzero(classes == "PN").tolist())
        reached_pn = {
            int(dst) for src, dst in zip(coo.row.tolist(), coo.col.tolist())
            if int(src) in orn_rows and int(dst) in pn_rows
        }
        attached = np.asarray(sorted(reached_pn), dtype=np.int64)
        admissible = np.asarray(
            sorted(set(kc_mbon_rows.tolist()) | set(attached.tolist())), dtype=np.int64
        )
        kept, reasons = _cap_by_frontier(raw_graph, root_ids, admissible, target_n)
        if kept.size == 0:
            raise CandidateError("S2: the MB/KC-centred admissible set is empty")
        adjacency = raw_graph[kept][:, kept].tocsr()
        prov = _provenance(
            candidate_id="S2",
            selection_rule=(
                "MB/KC-centred: seed = KC, higher_order, MBON, DAN populations; ORN/PN "
                "attached by real ORN->PN edges (only PNs an ORN actually reaches); "
                "capped in degree order within the admissible set"
            ),
            seed_populations={
                c: int((classes == c).sum()) for c in ("KC", "higher_order", "MBON", "DAN")
            },
            added_populations={
                c: int((classes[kept] == c).sum()) for c in ("ORN", "PN", "KC", "higher_order", "MBON", "DAN")
            },
            frontier_rule="total degree within the admissible set, ties by root id",
            cap_rule=f"target_n={target_n}",
            classes=classes,
            node_rows=kept,
            adjacency=adjacency,
            admission_reason={
                **{f"seed:{k}": int(v) for k, v in reasons.items()},
                "orn_reached_pn_attached": int(attached.size),
            },
            extra={"n_orn_reached_pn": int(attached.size)},
        )
        return CandidateSubstrate(
            "S2", kept, root_ids[kept], adjacency,
            _input_rows(classes, kept), prov,
        )

    raise CandidateError(f"unhandled candidate {candidate_id!r}")  # pragma: no cover


def _input_rows(classes: np.ndarray, node_rows: np.ndarray) -> np.ndarray:
    """The declared input-receiving rows: every typed node in the candidate, in row order.

    The input *rule* is identical for every candidate (amendment 2/3's typed-aligned
    mapping); which nodes it lands on follows from the candidate's own typed composition,
    so the candidates' S1 values differ because the substrates differ, never because the
    input rule was changed between them.
    """
    here = classes[node_rows]
    return np.flatnonzero(np.isin(here, ["ORN", "PN", "KC"])).astype(np.int64)


def build_candidate_input(candidate: CandidateSubstrate, annotation, din: int, *, seed: int = 0):
    """Build the candidate's ``W_in`` with the SAME declared rule for every candidate.

    One channel per receiving node, the amendment-2 per-layer Din allocation, density within
    amendment 3's ceiling. ``B`` is never rescaled per candidate: identical input rule, so S1
    compares substrates rather than input scales.
    """
    from drososense.reservoir.input_mapping import build_typed_aligned_mapping

    # density_limit is raised here only as far as the declared amendment-3 ceiling; the
    # receiving_fraction is fixed across candidates so the *rule* is identical.
    mapping = build_typed_aligned_mapping(
        candidate.root_ids, annotation, din, seed=seed, receiving_fraction=0.80,
        density_limit=0.16,
    )
    return mapping


__all__ = [
    "CANDIDATE_IDS",
    "CandidateError",
    "CandidateSubstrate",
    "build_candidate_input",
    "generate_candidate",
]